seed: 42
output_dir: runs
report_file: runs/report.json
table_file: runs/summary.tsv

# Shared dataset settings; actual manifests/overrides are layered via configs/overrides/**
dataset:
  name: togethercomputer/RedPajama-Data-V2
  subset: sample
  split: train
  text_field: text
  streaming: false
  local_cache_dir: data/cache
  prefetch:
    enabled: true
    split: sample/train
    force_download: false
  data_files:
    train: data/shards/train.parquet
    validation: data/shards/val.parquet
    test: data/shards/test.parquet

# Chunking defaults aligned with the experiment contract.
dedup:
  chunk_tokens: 1024
  stride_tokens: 1024
  min_chunk_tokens: 256
  lowercase: true
  strip_html: true
  collapse_whitespace: true
  cross_split: true
  near:
    enabled: true
    shingle_size: 5
    num_permutations: 128
    band_size: 4
    threshold: 0.85
    skip_short_tokens: 256

training:
  block_size: 1024
  n_layer: 12
  n_head: 12
  n_embd: 768
  dropout: 0.1
  lr: 0.00025
  weight_decay: 0.1
  betas: [0.9, 0.95]
  grad_clip: 1.0
  batch_size: 8
  max_steps: 100000
  warmup_steps: 2000
  eval_interval: 5000
  log_interval: 100
  device: auto
  precision: bf16
  max_train_tokens: 3000000000
  save_checkpoints: true

evaluation:
  val_batch_size: 8
  max_val_tokens: 1048576
  downstream_tasks:
    lambada_openai: 500
    piqa: 500
    hellaswag: 500
  canary_prompts: 100
  canary_decode_max_tokens: 32

runs: []  # Individual launcher scripts will compose run configs per condition.
